### ISSUE TITLE
Repeatable crash when more than one search engine is set to "default"

### ISSUE THREAD

**Issue by Quix0r** [beniz/seeks#17]
If 2 or more external search engines are set as default in "websearch-config" seeks crashes. The fix is to use only one search engine as default. Btw: Only google works.

The crash happens after this message:
Operation timed out after 3001 milliseconds with 0 bytes received

**Comment by Quix0r** [comment]
A backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd27fc700 (LWP 21299)]
0x00000030a2ac0e91 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00000030a2ac0e91 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff3feb8a6 in operator= (__str=..., this=0x18) at /usr/include/c++/4.7/bits/basic_string.h:544
#2  seeks_plugins::search_snippet::set_title (this=0x0, title=...) at search_snippet.cpp:477
#3  0x00007ffff4013775 in seeks_plugins::se_parser_yahoo::end_element (this=0x67b350, pc=0x7fffd27fbae0, 
    name=0x7fffd40208be "h3") at se_parser_yahoo.cpp:171
#4  0x0000003abd0771f1 in ?? () from /usr/lib/x86_64-linux-gnu/libxml2.so.2
#5  0x0000003abd07aa2e in htmlParseChunk () from /usr/lib/x86_64-linux-gnu/libxml2.so.2
#6  0x00007ffff400f955 in seeks_plugins::se_parser::parse_output (this=<optimized out>, 
    output=0x7fffdc0df8d8 "<!doctype html><html id=\"Stencil\" class=\"NoJs\" lang=\"en-US\"><head><meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"><link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://l.yimg.com/"..., 
    snippets=<optimized out>, count_offset=<optimized out>) at se_parser.cpp:246
#7  0x00007ffff3fe2012 in seeks_plugins::se_handler::parse_output (args=...) at se_handler.cpp:967
#8  0x00000035d5806b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00000035d50db95d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in ?? ()
```

**Comment by beniz** [comment]
Does the yahoo parser still works ?

**Comment by Quix0r** [comment]
No, seems to cause the crash. :-(
